[package]
name = "sel4_vspace"
version = "0.1.0"
edition = "2021"

[dependencies]
sel4_cspace = { git = "https://github.com/rel4team/sel4_cspace.git" }
sel4_common = { git = "https://github.com/rel4team/sel4_common.git" }
riscv = { git = "https://gitee.com/rcore-os/riscv", features = ["inline-asm"] }


[features]
ENABLE_SMP = []